#!/bin/bash

CID=$1
CONTAINER_IP=$2
GATEWAY=172.20.0.1
TEMPLATE_ENGLISH=/var/lib/vz/dump/english_all_system.tar
TEMPLATE_HASH=/var/lib/vz/dump/hashed_all_system.tar

if [ $3 -ne 0 ]
then
kill -9 $3
fi

killall set_up_$CID

pct stop $CID
pct unmount $CID

echo PLEASE STOP
umount -l /dev/pve/vm-$CID-disk-1

pct destroy $CID
if [ $(( $RANDOM % 2 )) -eq 0 ]
then
pct create $CID $TEMPLATE_ENGLISH --storage local-lvm --net0 name=eth0,bridge=vmbr0,ip=$CONTAINER_IP/16,gw=$GATEWAY --onboot 1 --nameserver 1.1.1.1 --searchdomain umd.edu --core 1 --cpulimit 0.5 --swap 0 --memory 512
else
pct create $CID $TEMPLATE_HASH --storage local-lvm --net0 name=eth0,bridge=vmbr0,ip=$CONTAINER_IP/16,gw=$GATEWAY --onboot 1 --nameserver 1.1.1.1 --searchdomain umd.edu --core 1 --cpulimit 0.5 --swap 0 --memory 512
fi
pct start $CID
pct mount $CID
sed -i "s/PermitRootLogin prohibit-password/PermitRootLogin yes/" /var/lib/lxc/$CID/rootfs/etc/ssh/sshd_config
echo  "root:proxmoxContainer@ACES" | pct exec $CID chpasswd
echo "TMOUT=1800" >> /var/lib/lxc/$CID/rootfs/etc/bash.bashrc

pct exec $CID -- service ssh restart

nohup ~/set_up_10X $1 $2 $4 >> ~/output_$CID &

